services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - decathlon-home:/home/node
      - decathlon-node-modules:/workspace/node_modules
    ports:
      - "3000:3000"
    environment:
      - PROJECT_NAME=decathlon
      - SUPABASE_PROJECT_ID=ymudzmawcwkoubiqfjbt
    env_file:
      - ../.env.local
    stdin_open: true
    tty: true
    command: sleep infinity

volumes:
  decathlon-home:
  decathlon-node-modules:
